casDB = ["NGG","NGCG","NGAG","NGAN","NNGRRT","NNNNGATT","NNAGAAW","NAAAAC","NNNVRYM","TTTN","NNGTGA","TTN","NGT","NGG","GGC","HGA","NNNRRT","TATV","TYCV","TGTV","VTTV","TTTT","TTCN","NNVRRN","NNVACT","NNVATG","NNVATT","NNVGCT","NNVGTG","NNVGTT","NG"]
CASletter = {
                "N":["A","C","T","G"],
                "A":["A"],
                "C":["C"],
                "T":["T"],
                "G":["G"],
                "U":["U"],
                "W": ["A","T"],
                "S": ["C","G"],
                "M": ["A","C"],
                "K": ["G","T"],
                "R": ["A","G"],
                "Y": ["C","T"],
                "B": ["C","G","T"],
                "D": ["A","G","T"],
                "H": ["A","C","T"],
                "V": ["A","C","G"],

}
CASnames = {
    "NGG":"SpCas9",
    "NGCG":"VRER SpCas9",
    "NGAG":"EQR SpCas9",
    "NGAN":"VQR SpCas9",
    "NNGRRT":"SaCas9",
    "NNNRRT":"KKH SaCas9",
    "NNNNGATT":"NmCas9",
    "NNAGAAW":"StCas9",
    "NAAAAC":"TdCas9",
    "NNNVRYM":"CjCas9",
    "NNGTGA":"SpCas9 (From Strep)",
    "TTTN":"LbCpf1 & AsCpf1",
    "TTN":"FnCpf1",
    "NGG":"xCas9",
    "NGT":"xCas9",
    "GGC":"xCas9",
    "HGA":"xCas9",
    "TATV":"AsCas12a RVR",
    "TYCV":"AsCas12a RR",
    "TGTV":"enAsCas12a",
    "VTTV":"enAsCas12a",
    "TTTT": "enAsCas12a",
    "TTCN": "enAsCas12a",
    "NNVRRN": "cCas9",
    "NNVACT": "cCas9",
    "NNVATG": "cCas9",
    "NNVATT": "cCas9",
    "NNVGCT": "cCas9",
    "NNVGTG": "cCas9",
    "NNVGTT": "cCas9",
    "NG": "SpCas9-NG",
}